name: Test Minimal

on:
  push:
    branches:
      - clean-xonai-branch
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install package only
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    
    - name: Import test
      run: |
        python -c "import xonai; print(f'xonai version: {xonai.__version__}')"